vendor: reef
name: text_line
category: text
assets:
    component_image: ../../../assets/img/text-freeform.svg
basicLocale:
    title: rf_field_title
    placeholder: rf_field_placeholder
advancedLocale:
    rf_error_required_empty: rf_error_required_empty_title
internalLocale:
    error_regexp:
    error_value_too_long:
    rf_submission_empty_value:
basicDefinition:
    fields:
      - component: reef:condition
        name: 'required'
        locales:
            en_US:
                title: 'Required'
            nl_NL:
                title: 'Verplicht'
      - component: reef:text_line
        name: 'default'
        locales:
            en_US:
                title: 'Default value'
            nl_NL:
                title: 'Standaardwaarde'
advancedDefinition:
    fields:
      - component: reef:text_number
        name: 'max_length'
        default: 1000
        min: 0
        step: 1
        locales:
            en_US:
                title: 'Max. input length'
            nl_NL:
                title: 'Max. aantal tekens'
props:
  - name: 'regexp'
    default: null
builder_operators:
    eq: equals
    neq: does not equal
    in: contains
    nin: does not contain
    start: starts with
    nstart: does not start with
    end: ends with
    nend: does not end with
    empty: is empty
    nempty: is not empty
    longer: is longer than
    shorter: is shorter than
builder_dependencies:
  - reef:text_line
  - reef:text_number
_builder_operators:
  - operators:
        eq: equals
        neq: does not equal
        in: contains
        nin: does not contain
        start: starts with
        nstart: does not start with
        end: ends with
        nend: does not end with
    operand:
        component: reef:text_line
  - operators:
        empty: is empty
        nempty: is not empty
    operand: null
  - operators:
        longer: is longer than
        shorter: is shorter than
    operand:
        component: reef:text_number
        min: 0
