vendor: reef
name: text_line
category: text
assets:
    component_image: ../../../assets/img/text-freeform.svg
basicLocale:
    title: rf_field_title
    placeholder: rf_field_placeholder
internalLocale:
    error_regexp:
    error_value_too_long:
    rf_submission_empty_value:
basicDefinition:
    fields:
      - component: reef:text_line
        name: 'default'
        locales:
            en_US:
                title: 'Default value'
            nl_NL:
                title: 'Standaardwaarde'
advancedDefinition:
    fields:
      - component: reef:text_number
        name: 'max_length'
        default: 1000
        min: 0
        step: 1
        locales:
            en_US:
                title: 'Max. input length'
            nl_NL:
                title: 'Max. aantal tekens'
props:
  - name: 'regexp'
    default: null
builder_operators:
    eq: equals
    neq: does not equal
    match: matches
    nmatch: does not match
    empty: is empty
    nempty: is not empty
    longer: is longer than
    shorter: is shorter than
