vendor: reef
name: option_list
category: text
assets:
    component_image: ../../../assets/img/text-freeform.svg
basicLocale:
    title: rf_field_title
internalLocale:
    option_name_title:
    option_title_title:
    add_button:
    error_min_options:
    error_max_options:
    error_max_checked_defaults:
    error_regexp:
    error_duplicate:
    rf_yes:
    rf_no:
    delete_option_confirm:
basicDefinition:
    fields:
      - component: reef:text_number
        name: 'min_num_options'
        min: 0
        step: 1
        default: 2
        locales:
            en_US:
                title: 'Min. number of options'
            nl_NL:
                title: 'Min. aantal opties'
      - component: reef:text_number
        name: 'max_num_options'
        min: 0
        step: 1
        locales:
            en_US:
                title: 'Max. number of options'
            nl_NL:
                title: 'Max. aantal opties'
      - component: reef:text_number
        name: 'max_checked_defaults'
        min: 0
        step: 1
        locales:
            en_US:
                title: 'Max. number of checked defaults'
            nl_NL:
                title: 'Max. aantal aangevinkte opties'
      - component: reef:text_number
        name: 'default_num_options'
        min: 0
        step: 1
        default: 3
        locales:
            en_US:
                title: 'Default number of options'
            nl_NL:
                title: 'Standaard aantal opties'
advancedDefinition:
    fields:
      - component: reef:checkbox
        name: 'names'
        default: true
        locales:
            en_US:
                title: 'Ask field names'
            nl_NL:
                title: 'Vraag veld namen'
      - component: reef:option_list
        name: 'default'
        locales:
            en_US:
                title: 'Default options'
            nl_NL:
                title: 'Standaard opties'