vendor: reef
name: text_number
category: text
assets:
    component_image: ../../../assets/img/text-number.svg
basicLocale:
    title: rf_field_title
    placeholder: rf_field_placeholder
advancedLocale:
    error_not_a_number: error_not_a_number_title
    error_number_min: error_number_min_title
    error_number_max: error_number_max_title
    error_number_min_max: error_number_min_max_title
internalLocale:
    rf_submission_empty_value:
basicDefinition:
    fields:
      - component: reef:text_number
        name: 'default'
        locales:
            en_US:
                title: 'Default value'
            nl_NL:
                title: 'Standaardwaarde'
advancedDefinition:
    fields:
      - component: reef:text_number
        name: 'min'
        locales:
            en_US:
                title: 'Minimum'
            nl_NL:
                title: 'Minimum'
      - component: reef:text_number
        name: 'max'
        locales:
            en_US:
                title: 'Maximum'
            nl_NL:
                title: 'Maximum'
      - component: reef:text_number
        name: 'step'
        locales:
            en_US:
                title: 'Step'
            nl_NL:
                title: 'Stap'
builder_operators:
    eq: equals
    neq: does not equal
    gte: is at least
    lte: is at most
