vendor: reef
name: text_number
category: text
image: text-number.svg
valueLocale:
    title: Field title
    placeholder: Placeholder
configLocale:
    error_not_a_number: Validation error
    error_number_min: Minimum error
    error_number_max: Maximum error
    error_number_min_max: Min/max error
    rf_error_required_empty: Required error
definition:
    fields:
      - component: reef:single_checkbox
        name: 'required'
        locales:
            en_US:
                title_right: 'Required'
            nl_NL:
                title_right: 'Verplicht'
      - component: reef:text_number
        name: 'default'
        locales:
            en_US:
                title: 'Default value'
            nl_NL:
                title: 'Standaardwaarde'
      - component: reef:text_number
        name: 'min'
        locales:
            en_US:
                title: 'Minimum'
            nl_NL:
                title: 'Minimum'
      - component: reef:text_number
        name: 'max'
        locales:
            en_US:
                title: 'Maximum'
            nl_NL:
                title: 'Maximum'
      - component: reef:text_number
        name: 'step'
        locales:
            en_US:
                title: 'Step'
            nl_NL:
                title: 'Stap'
