vendor: reef
name: checklist
category: choice
assets:
    component_image: ../../../assets/img/choice-checklist.svg
basicLocale:
    title: rf_field_title
basicDefinition:
    fields:
      - component: reef:option_list
        name: 'options'
        min_num_options: 2
        default_num_options: 2
        locales:
            en_US:
                title: 'Options'
            nl_NL:
                title: 'Opties'
builder_operators:
    has: has checked
    nhas: has not checked
    gte: at least checked
    lte: at most checked
    gten: at least unchecked
    lten: at most unchecked
