vendor: reef
name: textarea
category: text
documentation: https://reef-docs.readthedocs.io/en/latest/components/reef/textarea.html
assets:
    component_image: ../../../assets/img/text-textarea.svg
basicLocale:
    title: rf_field_title
    placeholder: rf_field_placeholder
internalLocale:
    error_value_too_long:
    rf_submission_empty_value:
basicDefinition:
    fields:
      - component: reef:textarea
        name: 'default'
        locales:
            en_US:
                title: 'Default value'
            nl_NL:
                title: 'Standaardwaarde'
advancedDefinition:
    fields:
      - component: reef:text_number
        name: 'max_length'
        default: 15000
        min: 0
        step: 1
        locales:
            en_US:
                title: 'Max. input length'
            nl_NL:
                title: 'Max. aantal tekens'
builder_operators:
    empty: is empty
    nempty: is not empty
    longer: is longer than
    shorter: is shorter than
