vendor: reef
name: textarea
category: text
assets:
    component_image: ../../../assets/img/text-textarea.svg
basicLocale:
    title: rf_field_title
    placeholder: rf_field_placeholder
advancedLocale:
    rf_error_required_empty: rf_error_required_empty_title
internalLocale:
    error_value_too_long:
    rf_submission_empty_value:
basicDefinition:
    fields:
      - component: reef:checkbox
        name: 'required'
        locales:
            en_US:
                title_right: 'Required'
            nl_NL:
                title_right: 'Verplicht'
      - component: reef:textarea
        name: 'default'
        locales:
            en_US:
                title: 'Default value'
            nl_NL:
                title: 'Standaardwaarde'
advancedDefinition:
    fields:
      - component: reef:text_number
        name: 'max_length'
        default: 15000
        min: 0
        step: 1
        locales:
            en_US:
                title: 'Max. input length'
            nl_NL:
                title: 'Max. aantal tekens'
