vendor: reef
name: paragraph
category: static
documentation: https://reef-docs.readthedocs.io/en/latest/components/reef/paragraph.html
assets:
    component_image: ../../../assets/img/static-paragraph.svg
basicLocale:
    content:
        title_key: content_title
        type: textarea
basicDefinition:
    fields: []
