vendor: reef
name: paragraph
category: static
assets:
    component_image: ../../../assets/img/static-paragraph.svg
basicLocale:
    content:
        title_key: content_title
        type: textarea
basicDefinition:
    fields: []
