vendor: reef
name: hidden
category: text
image: text-freeform.svg
basicDefinition:
    fields:
      - component: reef:text_line
        name: 'default'
        locales:
            en_US:
                title: 'Value'
            nl_NL:
                title: 'Waarde'
