vendor: reef
name: upload
category: other
assets:
    component_image: ../../../assets/img/other-upload.svg
basicLocale:
    title: rf_field_title
internalLocale:
    rf_submission_empty_value:
    error_too_many_files:
    error_max_size:
    error_file_type:
    error_still_uploading:
basicDefinition:
    fields:
      - component: reef:checkbox
        name: 'multiple'
        locales:
            en_US:
                title_right: 'Multiple files'
            nl_NL:
                title_right: 'Meerdere bestanden'
      - component: reef:text_number
        name: 'max_files'
        min: 1
        max: 20
        step: 1
        visible: 'multiple is checked'
        locales:
            en_US:
                title: 'Max. files'
            nl_NL:
                title: 'Max. aantal bestanden'
advancedDefinition:
    fields:
      - component: reef:checklist
        name: 'types'
        options: []
        locales:
            en_US:
                title: 'Accepted types'
            nl_NL:
                title: 'Geaccepteerde types'
builder_operators:
    empty: is empty
    nempty: is not empty
