vendor: reef
name: heading
category: static
image: static-heading.svg
basicLocale:
    title: heading_content_title
basicDefinition:
    fields:
      - component: reef:text_number
        name: 'size'
        min: 1
        max: 6
        step: 1
        default: 4
        required: true
        locales:
            en_US:
                title: 'Size'
            nl_NL:
                title: 'Grootte'
