vendor: reef
name: heading
category: static
documentation: https://reef-docs.readthedocs.io/en/latest/components/reef/heading.html
assets:
    component_image: ../../../assets/img/static-heading.svg
basicLocale:
    title: heading_content_title
basicDefinition:
    fields:
      - component: reef:text_number
        name: 'level'
        min: 1
        max: 6
        step: 1
        default: 1
        locales:
            en_US:
                title: 'Level'
            nl_NL:
                title: 'Niveau'
