vendor: reef
name: heading
category: static
image: text-freeform.svg
valueLocale:
    title: Heading content
configLocale: []
definition:
    fields:
      - component: reef:text_number
        name: 'size'
        min: 1
        max: 6
        step: 1
        default: 4
        locales:
            en_US:
                title: 'Size'
            nl_NL:
                title: 'Grootte'
