vendor: reef
name: single_line_text
category: text
image: text-freeform.svg
basicLocale:
    title: Field title
    placeholder: Placeholder
advancedLocale:
    rf_error_required_empty: Required error
internalLocale:
    error_regexp:
    error_value_too_long:
basicDefinition:
    fields:
      - component: reef:single_checkbox
        name: 'required'
        locales:
            en_US:
                title_right: 'Required'
            nl_NL:
                title_right: 'Verplicht'
      - component: reef:single_line_text
        name: 'default'
        locales:
            en_US:
                title: 'Default value'
            nl_NL:
                title: 'Standaardwaarde'
advancedDefinition:
    fields:
      - component: reef:text_number
        name: 'max_length'
        required: true
        default: 1000
        min: 0
        step: 1
        locales:
            en_US:
                title: 'Max. input length'
            nl_NL:
                title: 'Max. aantal tekens'
props:
  - name: 'regexp'
    default: null
