vendor: reef
name: checkbox
category: choice
documentation: https://reef-docs.readthedocs.io/en/latest/components/reef/checkbox.html
assets:
    component_image: ../../../assets/img/choice-check.svg
basicLocale:
    title: rf_field_title
    box_label: box_label_title
basicDefinition:
    fields:
      - component: reef:checkbox
        name: 'default'
        locales:
            en_US:
                box_label: 'Checked by default'
            nl_NL:
                box_label: 'Standaard aangevinkt'
builder_operators:
    checked: is checked
    nchecked: is not checked
