vendor: reef
name: checkbox
category: choice
assets:
    component_image: ../../../assets/img/choice-check.svg
basicLocale:
    title_left: title_left_title
    title_right: title_right_title
basicDefinition:
    fields:
      - component: reef:checkbox
        name: 'default'
        locales:
            en_US:
                title_right: 'Checked by default'
            nl_NL:
                title_right: 'Standaard aangevinkt'
builder_operators:
    checked: is checked
    nchecked: is not checked
