vendor: reef
name: checkbox
category: choice
image: choice-check.svg
basicLocale:
    title_left: title_left_title
    title_right: title_right_title
advancedLocale:
    rf_error_required_empty: rf_error_required_empty_title
basicDefinition:
    fields:
      - component: reef:checkbox
        name: 'required'
        locales:
            en_US:
                title_right: 'Required'
            nl_NL:
                title_right: 'Verplicht'
      - component: reef:checkbox
        name: 'default'
        locales:
            en_US:
                title_right: 'Checked by default'
            nl_NL:
                title_right: 'Standaard aangevinkt'
