vendor: reef
name: single_checkbox
category: choice
image: choice-check.svg
basicLocale:
    title_left: Left title
    title_right: Right title
advancedLocale:
    rf_error_required_empty: Required error
basicDefinition:
    fields:
      - component: reef:single_checkbox
        name: 'required'
        locales:
            en_US:
                title_right: 'Required'
            nl_NL:
                title_right: 'Verplicht'
      - component: reef:single_checkbox
        name: 'default'
        locales:
            en_US:
                title_right: 'Checked by default'
            nl_NL:
                title_right: 'Standaard aangevinkt'
