vendor: reef
name: condition
category: other
assets:
    component_image: ../../../assets/img/choice-check.svg
basicLocale:
    title: rf_field_title
internalLocale:
    rf_yes:
    rf_no:
    field_delete_condition_confirm:
    boolean_lose_condition_confirm:
    choose_field:
    condition_delete_confirm:
    condition_UI:
    condition_manual:
    operation_field:
    operation_operator:
    operation_operand:
    condition_and:
    condition_or:
basicDefinition:
    fields:
      - component: reef:condition
        name: 'default'
        locales:
            en_US:
                title: 'Default'
            nl_NL:
                title: 'Standaard'
